In [2]:
import numpy as np
import pandas as pd


In [4]:
df = pd.read_csv('dataFrames/numpy/Ciudades_Visitadas_Latinoamerica_2023.csv')
df

Ciudad       País  Población  Visitantes
0   Ciudad de México     México    9265833    21000000
1       Buenos Aires  Argentina    3059574    15000000
2     Río de Janeiro     Brasil    6748314    13000000
3               Lima       Perú    9756020     9000000
4             Bogotá   Colombia    7181663     8000000
5  Santiago de Chile      Chile    6199241     7500000
6          São Paulo     Brasil   12333146    20000000
7          La Habana       Cuba    2164182     4000000
8             Cancún     México     888124     5000000
9          Cartagena   Colombia    1036671     3000000

In [5]:
df['Población'].mean()

5863276.8

In [6]:
#redondear con numpy
np.round(df['Población'].mean())

5863277.0

In [7]:
np.min(df['Visitantes'])

3000000

In [8]:
np.max(df['Visitantes'])

21000000

<h2>Arrays en Numpy</h2>

In [9]:
mi_array = np.array([1,2,3,4,5])
mi_array

array([1, 2, 3, 4, 5])

In [10]:
type(mi_array)

numpy.ndarray

In [11]:
lista_grande = list(range(1000000))
array_grande = np.array(lista_grande)


In [12]:
type(mi_array)


numpy.ndarray

In [13]:
type(lista_grande)

list

In [15]:
import time
inicio_lista = time.time()
for i in lista_grande:
    i**2
fin_lista = time.time()
print(f'Tiempo con listas: {fin_lista - inicio_lista}')

Tiempo con listas: 0.06406617164611816


In [16]:
inicio_array = time.time()

array_grande ** 2
fin_array = time.time()
print(f'Tiempo con arrays: {fin_array - inicio_array}')

Tiempo con arrays: 0.003999948501586914


In [17]:
array = np.array([1,2,3])
len(array)

3

In [18]:
array.shape

(3,)

In [19]:
array_2d = np.array([[1,2,3],[4,5,6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
len(array_2d)

2

In [ ]:
#Crea un array unidimensional llamado: array_enteros que contenga los primeros 10 números enteros positivos, comenzando desde el 1.
array_enteros = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
#Utilizando el array creado en el Ejercicio 1,  array_enteros escribe un código que imprima la forma de este array, debes almacenar el resultado en una variable llamada: forma_array

array_enteros = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
forma_array = array_enteros.shape
print(forma_array)

In [21]:
x = [1,2,3]
y = [4,5,6]
z = [7,8,9]


In [22]:
np.concatenate((x,y,z))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a = [[1,2],
     [3,4]]
b = [[5,6],
     [7,8]]
np.concatenate((a,b), axis=1) 


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [25]:
array_concatenado = np.concatenate((a,b), axis=1) 
array_concatenado.shape

(2, 4)

In [27]:
array_reformado = array_concatenado.reshape(4,2)
array_reformado

array([[1, 2],
       [5, 6],
       [3, 4],
       [7, 8]])

In [29]:
array_sumado = array_reformado + array_reformado
array_sumado

array([[ 2,  4],
       [10, 12],
       [ 6,  8],
       [14, 16]])

In [30]:
raices = np.sqrt(array_sumado)
raices

array([[1.41421356, 2.        ],
       [3.16227766, 3.46410162],
       [2.44948974, 2.82842712],
       [3.74165739, 4.        ]])

<h2>Acceder a elementos de Array</h2>

In [31]:
array1d = np.array([1,2,3,4,5])
array2d = np.array([[1,2,3],[4,5,6], [7,8,9]])

In [ ]:
array2d[0]  # Primer fila

array([1, 2, 3])

In [33]:
array2d[1][2]  # Primer fila, primer columna

6

In [35]:
array2d[1,:]  # Segunda fila en adelante

array([4, 5, 6])

In [36]:
array2d[1, 1:3]

array([5, 6])

In [37]:
array2d[:2, :2]

array([[1, 2],
       [4, 5]])

In [38]:
#indexacion boolean
array2d > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [39]:
#Crea un array de numpy nombrado numeros que contenga los primeros 10 números enteros (del 1 al 10).
numeros = np.array([1,2,3,4,5,6,7,8,9,10])
quinto_elemento = numeros[4]
print(quinto_elemento)

5


In [41]:
""" 
Crea un array bidimensional al que nombres: matriz con forma (3, 3) 
que representa una matriz de números del 1 al 9.
 Escribe un código para extraer la segunda fila completa de esta matriz.
 Almacenala en una variable nombrada segunda_fila
"""
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
segunda_fila = matriz[1, :]
segunda_fila

array([4, 5, 6])

<h2>Forma y estructura de Arrays</h2>

In [46]:
array = np.array([1,2,3,4,5,6,7,8,9])
array 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
array_mod = array.reshape(3,3)
array_mod

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
array_mod2= array.reshape(-1, 3)
array_mod2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
array_volteado = array_mod2.transpose()
array_volteado

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [51]:
array_chato = array_mod.flatten()
array_chato

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
array_ravel = array_mod.ravel()
array_ravel

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
"""
Crea un array de NumPy llamado array_original  que contenga 
los números del 1 al 12 y luego cambia su forma para
 que se convierta en un array de 3 filas y 4 columnas.
 Almacenalo en una variable llamada array_reshape
"""
array_original = np.array(range(1, 13))
array_reshape = array_original.reshape(3, 4)
array_reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
array_original = np.array([[1,2,3], [4,5,6]])
array_original.shape

(2, 3)

In [57]:
array_modificado = array_original.transpose()
array_modificado

array([[1, 4],
       [2, 5],
       [3, 6]])

<h2>Broadcasting</h1>

In [58]:
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

In [59]:
array2 = np.array([[0],[10],[20],[30]])
array2

array([[ 0],
       [10],
       [20],
       [30]])

In [60]:
broadcast_suma = array1 + array2
broadcast_suma

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [61]:
broadcast_multi = array1 * array2
broadcast_multi

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [ ]:
#funciones universales
a = np.array([1,2,3])
b = np.array([4,5,6])


array([5, 7, 9])

In [65]:
resultado = np.add(a, b)
resultado

array([5, 7, 9])

In [67]:
resultado2 = np.exp(a)
resultado2

array([ 2.71828183,  7.3890561 , 20.08553692])

In [68]:
resultado3 = np.log(a)
resultado3

array([0.        , 0.69314718, 1.09861229])

In [70]:
resultado4 = np.log10(a)
resultado4


array([0.        , 0.30103   , 0.47712125])

In [73]:
resultado5 = np.sqrt(a)
resultado5

array([1.        , 1.41421356, 1.73205081])

<h2>Tratamiento numero faltantes</h2>

In [74]:
array = np.array([1, 2, np.nan, 4, 5])
array

array([ 1.,  2., nan,  4.,  5.])

In [75]:
np.isnan(array)

array([False, False,  True, False, False])

In [76]:
np.min(array)

nan

In [78]:
np.nanmean(array)


3.0

In [79]:
array_con_0 = np.where(np.isnan(array), 0, array)
array_con_0

array([1., 2., 0., 4., 5.])

In [81]:
promedio = np.mean(array_con_0)
array_con_promedio = np.where(np.isnan(array), promedio, array)
array_con_promedio

array([1. , 2. , 2.4, 4. , 5. ])

In [83]:

array_filtrado = array[~np.isnan(array)]
array_filtrado

array([1., 2., 4., 5.])

In [84]:

array_filtrado = array[np.isnan(array)]
array_filtrado

array([nan])

In [85]:
array = np.genfromtxt('dataFrames\pandas\medallas.csv')
array

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\matab\AppData\Local\Temp\ipykernel_23160\1134737076.py:1: SyntaxWarning: invalid escape sequence '\p'
  array = np.genfromtxt('dataFrames\pandas\medallas.csv')
C:\Users\matab\AppData\Local\Temp\ipykernel_23160\1134737076.py:1: SyntaxWarning: invalid escape sequence '\p'
  array = np.genfromtxt('dataFrames\pandas\medallas.csv')


ValueError: Some errors were detected !
    Line #15 (got 2 columns instead of 1)
    Line #17 (got 2 columns instead of 1)
    Line #20 (got 2 columns instead of 1)
    Line #22 (got 2 columns instead of 1)
    Line #24 (got 2 columns instead of 1)
    Line #27 (got 4 columns instead of 1)
    Line #36 (got 2 columns instead of 1)
    Line #39 (got 3 columns instead of 1)
    Line #44 (got 4 columns instead of 1)
    Line #63 (got 2 columns instead of 1)
    Line #65 (got 2 columns instead of 1)
    Line #70 (got 2 columns instead of 1)
    Line #72 (got 3 columns instead of 1)
    Line #73 (got 3 columns instead of 1)
    Line #74 (got 4 columns instead of 1)
    Line #77 (got 2 columns instead of 1)
    Line #78 (got 2 columns instead of 1)
    Line #82 (got 2 columns instead of 1)
    Line #86 (got 3 columns instead of 1)

In [90]:
array = np.genfromtxt('dataFrames\\numpy\\medallas (1).csv',delimiter=',')
array

array([[ nan,  nan,  nan,  nan,  nan],
       [ nan,   1.,   2.,   3.,  nan],
       [ nan,   2.,   2.,   4.,  nan],
       [ 17.,   7.,  22.,  46.,  nan],
       [  1.,   1.,   5.,   7.,  nan],
       [ nan,   3.,   4.,   7.,  nan],
       [  2.,  nan,  nan,   2.,  nan],
       [ nan,   1.,  nan,   1.,  nan],
       [  1.,   3.,   3.,   7.,  nan],
       [  3.,   1.,   3.,   7.,  nan],
       [  1.,  nan,  nan,   1.,  nan],
       [ nan,  nan,   1.,   1.,  nan],
       [  7.,   6.,   8.,  21.,  nan],
       [  3.,   1.,   2.,   6.,  nan],
       [ nan,  nan,   1.,   1.,  nan],
       [  7.,   6.,  11.,  24.,  nan],
       [  2.,   4.,   6.,  12.,  nan],
       [ nan,   4.,   1.,   5.,  nan],
       [  3.,   3.,   2.,   8.,  nan],
       [ nan,  nan,   1.,   1.,  nan],
       [  7.,   3.,   5.,  15.,  nan],
       [  4.,   4.,   3.,  11.,  nan],
       [  3.,   4.,   4.,  11.,  nan],
       [ nan,   3.,   2.,   5.,  nan],
       [  2.,   1.,  nan,   3.,  nan],
       [  1.,   1.,   4.,

In [89]:
array = np.genfromtxt('dataFrames\\numpy\medallas (1).csv',delimiter=',',filling_values=0)
array

<>:1: SyntaxWarning: invalid escape sequence '\m'
<>:1: SyntaxWarning: invalid escape sequence '\m'
C:\Users\matab\AppData\Local\Temp\ipykernel_23160\2396860756.py:1: SyntaxWarning: invalid escape sequence '\m'
  array = np.genfromtxt('dataFrames\\numpy\medallas (1).csv',delimiter=',',filling_values=0)


array([[  0.,   0.,   0.,   0.,   0.],
       [  0.,   1.,   2.,   3.,   0.],
       [  0.,   2.,   2.,   4.,   0.],
       [ 17.,   7.,  22.,  46.,   0.],
       [  1.,   1.,   5.,   7.,   0.],
       [  0.,   3.,   4.,   7.,   0.],
       [  2.,   0.,   0.,   2.,   0.],
       [  0.,   1.,   0.,   1.,   0.],
       [  1.,   3.,   3.,   7.,   0.],
       [  3.,   1.,   3.,   7.,   0.],
       [  1.,   0.,   0.,   1.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,   8.,  21.,   0.],
       [  3.,   1.,   2.,   6.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,  11.,  24.,   0.],
       [  2.,   4.,   6.,  12.,   0.],
       [  0.,   4.,   1.,   5.,   0.],
       [  3.,   3.,   2.,   8.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   3.,   5.,  15.,   0.],
       [  4.,   4.,   3.,  11.,   0.],
       [  3.,   4.,   4.,  11.,   0.],
       [  0.,   3.,   2.,   5.,   0.],
       [  2.,   1.,   0.,   3.,   0.],
       [  1.,   1.,   4.,

In [91]:
array = np.genfromtxt('dataFrames\\numpy\\medallas (1).csv',delimiter=',',filling_values=0, skip_header=1)
array

array([[  0.,   1.,   2.,   3.,   0.],
       [  0.,   2.,   2.,   4.,   0.],
       [ 17.,   7.,  22.,  46.,   0.],
       [  1.,   1.,   5.,   7.,   0.],
       [  0.,   3.,   4.,   7.,   0.],
       [  2.,   0.,   0.,   2.,   0.],
       [  0.,   1.,   0.,   1.,   0.],
       [  1.,   3.,   3.,   7.,   0.],
       [  3.,   1.,   3.,   7.,   0.],
       [  1.,   0.,   0.,   1.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,   8.,  21.,   0.],
       [  3.,   1.,   2.,   6.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,  11.,  24.,   0.],
       [  2.,   4.,   6.,  12.,   0.],
       [  0.,   4.,   1.,   5.,   0.],
       [  3.,   3.,   2.,   8.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   3.,   5.,  15.,   0.],
       [  4.,   4.,   3.,  11.,   0.],
       [  3.,   4.,   4.,  11.,   0.],
       [  0.,   3.,   2.,   5.,   0.],
       [  2.,   1.,   0.,   3.,   0.],
       [  1.,   1.,   4.,   6.,   0.],
       [ 39.,  41.,  33.,

In [92]:
array = np.genfromtxt('dataFrames\\numpy\\medallas (1).csv',delimiter=',',filling_values=0, skip_header=1, dtype=int)

array

array([[  0,   1,   2,   3,   0],
       [  0,   2,   2,   4,   0],
       [ 17,   7,  22,  46,   0],
       [  1,   1,   5,   7,   0],
       [  0,   3,   4,   7,   0],
       [  2,   0,   0,   2,   0],
       [  0,   1,   0,   1,   0],
       [  1,   3,   3,   7,   0],
       [  3,   1,   3,   7,   0],
       [  1,   0,   0,   1,   0],
       [  0,   0,   1,   1,   0],
       [  7,   6,   8,  21,   0],
       [  3,   1,   2,   6,   0],
       [  0,   0,   1,   1,   0],
       [  7,   6,  11,  24,   0],
       [  2,   4,   6,  12,   0],
       [  0,   4,   1,   5,   0],
       [  3,   3,   2,   8,   0],
       [  0,   0,   1,   1,   0],
       [  7,   3,   5,  15,   0],
       [  4,   4,   3,  11,   0],
       [  3,   4,   4,  11,   0],
       [  0,   3,   2,   5,   0],
       [  2,   1,   0,   3,   0],
       [  1,   1,   4,   6,   0],
       [ 39,  41,  33, 113,   0],
       [  1,   0,   1,   2,   0],
       [  1,   1,   2,   4,   0],
       [  1,   0,   1,   2,   0],
       [  0,  

In [93]:
array_ejemplo = np.array([[1,2,3],[4,5,6]])

In [94]:
np.savetxt('dataFrames\\numpy\\medallas_guardado.csv', array_ejemplo, delimiter=',', fmt='%d')

<h2>Pandas y Numpy</h2>

In [95]:
import pandas as pd
import numpy as np

In [96]:
df = pd.DataFrame({
    'Impares': [1,3,5],
    'Pares': [2,4,6]
})
df

Impares  Pares
0        1      2
1        3      4
2        5      6

In [99]:
array_np1 = df.values
array_np1

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int64)

In [100]:
array_np2 = df.to_numpy()
array_np2

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int64)

In [101]:
np.sqrt(df)

Impares     Pares
0  1.000000  1.414214
1  1.732051  2.000000
2  2.236068  2.449490

In [102]:
np.max(df)

6

In [103]:
#Numpy a Pandas
df_desde_np = pd.DataFrame(array_np1, columns=['Impares', 'Pares'])
df_desde_np

Impares  Pares
0        1      2
1        3      4
2        5      6

<h1>Analisis de datos Meteorologicos</h1>

In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.read_csv('dataFrames/numpy/datos_meteorologicos.csv')
df

Fecha  Temperatura  Precipitación    Humedad
0     01/01/2010    17.440675      10.957482  52.384637
1     02/01/2010    25.759468       5.315628  30.633530
2     03/01/2010    20.138169      15.317706  41.496715
3     04/01/2010    17.244159      13.151008  90.684704
4     05/01/2010    11.182740      16.413667  22.116422
...          ...          ...            ...        ...
5105  24/12/2023    -9.554692      12.700998  50.094533
5106  25/12/2023     2.837831       5.475686  92.456057
5107  26/12/2023    29.873597       4.615012  18.362847
5108  27/12/2023          NaN            NaN        NaN
5109  28/12/2023    37.308043       7.330510  50.646211

[5110 rows x 4 columns]

In [3]:
df.describe()

Temperatura  Precipitación      Humedad
count  4855.000000    4855.000000  4855.000000
mean     14.889296       9.901604    54.359061
std      14.440466       5.801842    26.096345
min      -9.996378       0.003008    10.014980
25%       2.651777       4.756907    31.866578
50%      14.693274       9.853698    54.254478
75%      27.381451      14.966997    77.029500
max      39.998201      19.999559    99.996582

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Fecha          5110 non-null   object 
 1   Temperatura    4855 non-null   float64
 2   Precipitación  4855 non-null   float64
 3   Humedad        4855 non-null   float64
dtypes: float64(3), object(1)
memory usage: 159.8+ KB


In [5]:
type(df['Fecha'])

pandas.core.series.Series

In [7]:
#convertir a datetime
df['Fecha'] = pd.to_datetime(df['Fecha'],format='%d/%m/%Y')
df['Fecha']

0      2010-01-01
1      2010-01-02
2      2010-01-03
3      2010-01-04
4      2010-01-05
          ...    
5105   2023-12-24
5106   2023-12-25
5107   2023-12-26
5108   2023-12-27
5109   2023-12-28
Name: Fecha, Length: 5110, dtype: datetime64[ns]

In [11]:
#sacar promedio de temperatura ignorando nulos
df_clean = df['Temperatura'].fillna(df['Temperatura'].mean())
df_clean.mean()


14.889295723531713

In [9]:
df_clean

Fecha  Temperatura  Precipitación    Humedad
0    2010-01-01    17.440675      10.957482  52.384637
1    2010-01-02    25.759468       5.315628  30.633530
2    2010-01-03    20.138169      15.317706  41.496715
3    2010-01-04    17.244159      13.151008  90.684704
4    2010-01-05    11.182740      16.413667  22.116422
...         ...          ...            ...        ...
5104 2023-12-23    -2.080426       4.361594  19.761457
5105 2023-12-24    -9.554692      12.700998  50.094533
5106 2023-12-25     2.837831       5.475686  92.456057
5107 2023-12-26    29.873597       4.615012  18.362847
5109 2023-12-28    37.308043       7.330510  50.646211

[4855 rows x 4 columns]

In [ ]:
#sacar promedio de temperatura de los primeros 6 meses
df_clean[:6].mean()

19.009986181448713

In [ ]:
#sacar total de precipitacion
df_precipitacion = df['Precipitación'].sum()
df_precipitacion

48072.28547172928

In [18]:
#maxima humedad registrada
df['Humedad'].max()

99.99658156071747

In [29]:
#sacar el dia con mayor humedad mostrando la humedad y la fecha
idx = df['Humedad'].idxmax()
fecha_max = df.loc[idx, 'Fecha']
humedad_max = df.loc[idx, 'Humedad']   # o df['Humedad'].max()
print(f"Mayor humedad: {humedad_max} registrada el {fecha_max}")


Mayor humedad: 99.99658156071747 registrada el 2023-01-21 00:00:00


In [ ]:
#sacar el dia con mayor temperatura mostrando la temperatura y la fecha
idx = df['Temperatura'].idxmax()
fecha_max = df.loc[idx, 'Fecha']
temperatura_max = df.loc[idx, 'Temperatura']   # o df['Temperatura'].max()
print(f"Mayor temperatura: {temperatura_max} registrada el {fecha_max}")

Mayor temperatura: 39.99820092713012 registrada el 2017-07-12 00:00:00


In [31]:
# sacar el dia con menor temperatura mostrando la temperatura y la fecha
idx = df['Temperatura'].idxmin()
fecha_min = df.loc[idx, 'Fecha']
temperatura_min = df.loc[idx, 'Temperatura']   # o df['Temperatura'].min()
print(f"Menor temperatura: {temperatura_min} registrada el {fecha_min}")

Menor temperatura: -9.996377518075391 registrada el 2020-07-23 00:00:00
